{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ml-service.fullname" . }}
  labels:
    {{- include "ml-service.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: http
      interval: 15s
  selector:
    matchLabels:
      {{- include "ml-service.selectorLabels" . | nindent 6 }}
{{- end }}